Docs: Update the React documentation to include changes to the `<OpenFormatProvider/>`
simpleweb/open-format pull request #100
Opened 2022-08-03 15:02 UTC by Sam-Archie

**What**:
Update to the documentation to display the requirement of a network option that needs to be passed to the provider for it to function as expected.

**Why**:
If the provider is not given a network, the provider, and therefore the SDK along with all of its functions will not work.

**How**:

Update to the docs to show this to anyone using it should avoid any confusion.
**Checklist**:

- [x] Documentation
- [ ] Tests "N/A"
- [ ] Code complete "N/A"
- [ ] Changeset  "N/A"

### Images
![Screenshot 2022-08-03 at 16 06 40](https://user-images.githubusercontent.com/68110533/182642760-1114f23e-5fc3-431b-a085-0c8fa3a05991.png)

2022-08-03 20:21 UTC, craigcoles requested changes
There is a few changes to tighten this all up.

It looks like your prettier is also changing all the quotes to single quotes. There isn't a problem with this, but would be good to just make sure all the examples are consistent.

2022-08-03 20:21 UTC, craigcoles commented on sdks/react/README.md
> +````
✂️  This needs removing

2022-08-03 20:21 UTC, craigcoles commented on sdks/react/README.md
> +````
Extra ` needs removing here

2022-08-03 20:21 UTC, craigcoles commented on sdks/react/README.md
> +      ></OpenFormatProvider>
```suggestion
      <OpenFormatProvider
        config={{ network: "https://matic-mumbai.chainstacklabs.com" }}
      >
        {/* the rest of your app... */}
      </OpenFormatProvider>
```

2022-08-03 20:21 UTC, craigcoles commented on sdks/react/README.md
> +- We have provided a hard coded example of a test network on mumbai. A full list of networks can found [here.](https://chainlist.org/)
```suggestion
- We have provided an example using a test network on Mumbai. A list of networks can found on [chainlist.org](https://chainlist.org/).
```

2022-08-03 20:21 UTC, craigcoles commented on sdks/react/README.md
> +- The provider accepts a config object where you set your network url.
```suggestion
- The provider accepts a config object where you set the network. This must be a full URL.
```

2022-08-04 09:18 UTC, Sam-Archie commented on sdks/react/README.md
> +      ></OpenFormatProvider>
✅

2022-08-04 09:44 UTC, KateHoward10 approved these changes

2022-08-09 09:11 UTC, craigcoles approved these changes

2022-08-09 09:25 UTC, merged